In [1]:
# import library
import numpy as np
import pandas as pd
import seaborn as sb
import os

In [3]:
# check dataframe
dataframe = pd.read_csv('glcm_dataset.csv')
dataframe.head()

Unnamed: 0                                            img_ids  \
0           0  0_rotated_by_15_Screen Shot 2018-06-08 at 4.59...   
1           1  0_rotated_by_15_Screen Shot 2018-06-08 at 4.59...   
2           2  0_rotated_by_15_Screen Shot 2018-06-08 at 4.59...   
3           3  0_rotated_by_15_Screen Shot 2018-06-08 at 5.00...   
4           4  0_rotated_by_15_Screen Shot 2018-06-08 at 5.00...   

   dissimilarity03  dissimilarity453  dissimilarity903  dissimilarity1353  \
0         0.041503          0.037354          0.039791           0.035011   
1         0.029879          0.029246          0.025833           0.027434   
2         0.032197          0.029996          0.030548           0.031839   
3         0.032509          0.030699          0.026471           0.032980   
4         0.030875          0.030136          0.034532           0.027231   

   correlation03  correlation453  correlation903  correlation1353  ...  \
0       0.909188        0.918181        0.913192         0.923314  ...   
1       0.919423        0.920366        0.930102         0.925301  ...   
2       0.913128        0.918641        0.917458         0.913641  ...   
3       0.920960        0.924862        0.935419         0.919280  ...   
4       0.932956        0.934274        0.924720         0.940611  ...   

   contrast13510    ASM010   ASM4510   ASM9010  ASM13510  energy010  \
0       0.094335  0.447883  0.454963  0.452034  0.470939   0.669241   
1       0.081263  0.568697  0.580163  0.579854  0.585728   0.754120   
2       0.097929  0.555136  0.570551  0.564463  0.558965   0.745074   
3       0.098221  0.524750  0.533611  0.540787  0.524336   0.724396   
4       0.082320  0.465861  0.467022  0.456423  0.477376   0.682540   

   energy4510  energy9010  energy13510        label  
0    0.674509    0.672335     0.686250  fresh_apple  
1    0.761684    0.761481     0.765329  fresh_apple  
2    0.755348    0.751308     0.747640  fresh_apple  
3    0.730487    0.735382     0.724110  fresh_apple  
4    0.683390    0.675591     0.690924  fresh_apple  

[5 rows x 195 columns]

In [4]:
# show label
os.listdir(
    'segmented_dataset'
)

['fresh_apple', 'stale_apple']

In [5]:
clean_data = dataframe.drop(columns=['Unnamed: 0', 'img_ids'])
clean_data = clean_data.replace({
    'fresh_apple': 0,
    'stale_apple': 1,
})
clean_data.head()


dissimilarity03  dissimilarity453  dissimilarity903  dissimilarity1353  \
0         0.041503          0.037354          0.039791           0.035011   
1         0.029879          0.029246          0.025833           0.027434   
2         0.032197          0.029996          0.030548           0.031839   
3         0.032509          0.030699          0.026471           0.032980   
4         0.030875          0.030136          0.034532           0.027231   

   correlation03  correlation453  correlation903  correlation1353  \
0       0.909188        0.918181        0.913192         0.923314   
1       0.919423        0.920366        0.930102         0.925301   
2       0.913128        0.918641        0.917458         0.913641   
3       0.920960        0.924862        0.935419         0.919280   
4       0.932956        0.934274        0.924720         0.940611   

   homogeneity03  homogeneity453  ...  contrast13510    ASM010   ASM4510  \
0       0.979248        0.981323  ...       0.094335  0.447883  0.454963   
1       0.985061        0.985377  ...       0.081263  0.568697  0.580163   
2       0.983901        0.985002  ...       0.097929  0.555136  0.570551   
3       0.983746        0.984651  ...       0.098221  0.524750  0.533611   
4       0.984563        0.984932  ...       0.082320  0.465861  0.467022   

    ASM9010  ASM13510  energy010  energy4510  energy9010  energy13510  label  
0  0.452034  0.470939   0.669241    0.674509    0.672335     0.686250      0  
1  0.579854  0.585728   0.754120    0.761684    0.761481     0.765329      0  
2  0.564463  0.558965   0.745074    0.755348    0.751308     0.747640      0  
3  0.540787  0.524336   0.724396    0.730487    0.735382     0.724110      0  
4  0.456423  0.477376   0.682540    0.683390    0.675591     0.690924      0  

[5 rows x 193 columns]

In [6]:
len(clean_data.columns)

193

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix


x = clean_data.iloc[:,:-1]
y = clean_data.iloc[:,-1:]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

scaler = MinMaxScaler()
x_train_scalled = scaler.fit_transform(x_train)
x_test_scalled = scaler.transform(x_test)

In [8]:
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

names = ["Nearest Neighbors", 
         "Linear SVM", 
         "RBF SVM", 
         "Decision Tree", 
         "Random Forest", 
         "Neural Network", 
         "Naive Bayes"]

classifiers = [
    KNeighborsClassifier(5),
    SVC(kernel="linear", C=0.025),
    SVC(gamma=2, C=1),
    DecisionTreeClassifier(),
    RandomForestClassifier(),
    MLPClassifier(max_iter=5000),
    GaussianNB(),
    ]

In [9]:
for name, model in zip(names, classifiers):
  model.fit(x_train_scalled, y_train.values.ravel())
  y_pred_model = model.predict(x_test_scalled)
  print(f'## MODEL NAME : {name}')
  print(confusion_matrix(y_test, y_pred_model))
  print(classification_report(y_test, y_pred_model))
  print('\n')

## MODEL NAME : Nearest Neighbors
[[134 221]
 [149 303]]
              precision    recall  f1-score   support

           0       0.47      0.38      0.42       355
           1       0.58      0.67      0.62       452

    accuracy                           0.54       807
   macro avg       0.53      0.52      0.52       807
weighted avg       0.53      0.54      0.53       807



## MODEL NAME : Linear SVM
[[  0 355]
 [  0 452]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       355
           1       0.56      1.00      0.72       452

    accuracy                           0.56       807
   macro avg       0.28      0.50      0.36       807
weighted avg       0.31      0.56      0.40       807





c:\Users\CATURWARGA COMPUTER\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\CATURWARGA COMPUTER\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\CATURWARGA COMPUTER\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to cont

## MODEL NAME : RBF SVM
[[ 66 289]
 [ 46 406]]
              precision    recall  f1-score   support

           0       0.59      0.19      0.28       355
           1       0.58      0.90      0.71       452

    accuracy                           0.58       807
   macro avg       0.59      0.54      0.50       807
weighted avg       0.59      0.58      0.52       807



## MODEL NAME : Decision Tree
[[155 200]
 [195 257]]
              precision    recall  f1-score   support

           0       0.44      0.44      0.44       355
           1       0.56      0.57      0.57       452

    accuracy                           0.51       807
   macro avg       0.50      0.50      0.50       807
weighted avg       0.51      0.51      0.51       807



## MODEL NAME : Random Forest
[[114 241]
 [113 339]]
              precision    recall  f1-score   support

           0       0.50      0.32      0.39       355
           1       0.58      0.75      0.66       452

    accuracy             

In [10]:
correlation = {}
label = clean_data['label']
for col in clean_data.columns:
  correlation[col] = label.corr(clean_data[col])
sorted_correlation = sorted(correlation.items(), key=lambda x: x[1])
print(sorted_correlation)
len(sorted_correlation)

[('dissimilarity453', -0.14971395589434416), ('contrast453', -0.14971395589434416), ('dissimilarity454', -0.14866363102169872), ('contrast454', -0.14866363102169872), ('dissimilarity455', -0.14826575057356114), ('contrast455', -0.14826575057356114), ('dissimilarity456', -0.14826575057356114), ('contrast456', -0.14826575057356114), ('dissimilarity457', -0.1447841951904973), ('contrast457', -0.1447841951904973), ('dissimilarity1353', -0.1418471783844126), ('contrast1353', -0.1418471783844126), ('dissimilarity903', -0.14111469866896276), ('contrast903', -0.14111469866896276), ('dissimilarity03', -0.14084034780978455), ('contrast03', -0.14084034780978455), ('dissimilarity458', -0.140395301310066), ('contrast458', -0.140395301310066), ('dissimilarity459', -0.140395301310066), ('contrast459', -0.140395301310066), ('dissimilarity1354', -0.1402569047958057), ('contrast1354', -0.1402569047958057), ('dissimilarity04', -0.1396381894653857), ('contrast04', -0.1396381894653857), ('dissimilarity904'

193

In [11]:
positive_corr = {}
negative_corr = {}
for (k,v) in sorted_correlation:
  if(v>0):
    positive_corr[k] = v
  else:
    negative_corr[k] = v
len(positive_corr)

129

In [12]:
from sklearn.decomposition import PCA

pca = PCA(n_components = len(positive_corr))
x_train_pca = pca.fit_transform(x_train_scalled)
x_test_pca = pca.transform(x_test_scalled)

In [13]:
for name, model in zip(names, classifiers):
  model.fit(x_train_pca, y_train.values.ravel())
  y_pred_model = model.predict(x_test_pca)
  try:
    print(f'## MODEL NAME : {name}')
    print(confusion_matrix(y_test, y_pred_model))
    print(classification_report(y_test, y_pred_model))
    print('\n')
  except:
    print("Hello!!!!")

## MODEL NAME : Nearest Neighbors
[[134 221]
 [149 303]]
              precision    recall  f1-score   support

           0       0.47      0.38      0.42       355
           1       0.58      0.67      0.62       452

    accuracy                           0.54       807
   macro avg       0.53      0.52      0.52       807
weighted avg       0.53      0.54      0.53       807



## MODEL NAME : Linear SVM
[[  0 355]
 [  0 452]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       355
           1       0.56      1.00      0.72       452

    accuracy                           0.56       807
   macro avg       0.28      0.50      0.36       807
weighted avg       0.31      0.56      0.40       807





c:\Users\CATURWARGA COMPUTER\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\CATURWARGA COMPUTER\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\CATURWARGA COMPUTER\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to cont

## MODEL NAME : RBF SVM
[[ 66 289]
 [ 46 406]]
              precision    recall  f1-score   support

           0       0.59      0.19      0.28       355
           1       0.58      0.90      0.71       452

    accuracy                           0.58       807
   macro avg       0.59      0.54      0.50       807
weighted avg       0.59      0.58      0.52       807



## MODEL NAME : Decision Tree
[[151 204]
 [184 268]]
              precision    recall  f1-score   support

           0       0.45      0.43      0.44       355
           1       0.57      0.59      0.58       452

    accuracy                           0.52       807
   macro avg       0.51      0.51      0.51       807
weighted avg       0.52      0.52      0.52       807



## MODEL NAME : Random Forest
[[105 250]
 [ 99 353]]
              precision    recall  f1-score   support

           0       0.51      0.30      0.38       355
           1       0.59      0.78      0.67       452

    accuracy             