In [1]:
import numpy as np
import pandas as pd
import seaborn as sb
import os

In [2]:
dataframe = pd.read_csv('merged_features.csv')
dataframe.head()

Unnamed: 0                        id  dissimilarity_0_3  \
0           0    1_Shaishe Date (2).JPG          11.825577   
1           1  2_Shaishe Date (114).JPG          11.812229   
2           2  0_Shaishe Date (106).JPG           9.650219   
3           3   0_Shaishe Date (18).JPG          12.294701   
4           4   1_Shaishe Date (71).JPG          12.105963   

   dissimilarity_45_3  dissimilarity_90_3  dissimilarity_135_3  \
0           10.044632           10.083512            11.400234   
1           10.840932           10.095559            11.027317   
2            9.567989           10.052463             8.903686   
3           10.564030           12.237651            12.381818   
4           11.011798           11.455904            11.519544   

   correlation_0_3  correlation_45_3  correlation_90_3  correlation_135_3  \
0         0.878916          0.905611          0.903054           0.886521   
1         0.841036          0.862395          0.873188           0.848192   
2         0.914970          0.917261          0.909626           0.926530   
3         0.853629          0.892255          0.856070           0.853879   
4         0.857570          0.872097          0.868072           0.871090   

   ...  246  247  248  249  250  251  252  253  254  label  
0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      6  
1  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      6  
2  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      6  
3  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      6  
4  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      6  

[5 rows x 450 columns]

In [3]:
os.listdir(
    'segmented-dataset'
)

['Shaishe',
 'Sokari',
 'Galaxy',
 'Meneifi',
 'Rutab',
 'Sugaey',
 'Nabtat Ali',
 'Medjool',
 'Ajwa']

In [4]:
clean_data = dataframe.drop(columns=['Unnamed: 0', 'id'])
clean_data = clean_data.replace({
    'Ajwa': 0,
    'Galaxy': 1,
    'Medjool': 2,
    'Meneifi': 3,
    'Nabtat Ali': 4,
    'Rutab': 5,
    'Shaishe': 6,
    'Sokari': 7,
    'Sugaey': 8
})
clean_data.head()


dissimilarity_0_3  dissimilarity_45_3  dissimilarity_90_3  \
0          11.825577           10.044632           10.083512   
1          11.812229           10.840932           10.095559   
2           9.650219            9.567989           10.052463   
3          12.294701           10.564030           12.237651   
4          12.105963           11.011798           11.455904   

   dissimilarity_135_3  correlation_0_3  correlation_45_3  correlation_90_3  \
0            11.400234         0.878916          0.905611          0.903054   
1            11.027317         0.841036          0.862395          0.873188   
2             8.903686         0.914970          0.917261          0.909626   
3            12.381818         0.853629          0.892255          0.856070   
4            11.519544         0.857570          0.872097          0.868072   

   correlation_135_3  homogeneity_0_3  homogeneity_45_3  ...  246  247  248  \
0           0.886521         0.264073          0.274423  ...  0.0  0.0  0.0   
1           0.848192         0.224594          0.230546  ...  0.0  0.0  0.0   
2           0.926530         0.359586          0.359693  ...  0.0  0.0  0.0   
3           0.853879         0.328971          0.328909  ...  0.0  0.0  0.0   
4           0.871090         0.306336          0.308445  ...  0.0  0.0  0.0   

   249  250  251  252  253  254  label  
0  0.0  0.0  0.0  0.0  0.0  0.0      6  
1  0.0  0.0  0.0  0.0  0.0  0.0      6  
2  0.0  0.0  0.0  0.0  0.0  0.0      6  
3  0.0  0.0  0.0  0.0  0.0  0.0      6  
4  0.0  0.0  0.0  0.0  0.0  0.0      6  

[5 rows x 448 columns]

In [5]:
len(clean_data.columns)

448

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix


x = clean_data.iloc[:,:-1]
y = clean_data.iloc[:,-1:]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

scaler = MinMaxScaler()
x_train_scalled = scaler.fit_transform(x_train)
x_test_scalled = scaler.transform(x_test)

In [7]:
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

names = ["Nearest Neighbors", 
         "Linear SVM", 
         "RBF SVM", 
         "Decision Tree", 
         "Random Forest", 
         "Neural Network", 
         "Naive Bayes"]

classifiers = [
    KNeighborsClassifier(5),
    SVC(kernel="linear", C=0.025),
    SVC(gamma=2, C=1),
    DecisionTreeClassifier(),
    RandomForestClassifier(),
    MLPClassifier(max_iter=10000),
    GaussianNB(),
    ]

In [8]:
for name, model in zip(names, classifiers):
  model.fit(x_train_scalled, y_train.values.ravel())
  y_pred_model = model.predict(x_test_scalled)
  print(f'## MODEL NAME : {name}')
  print(confusion_matrix(y_test, y_pred_model))
  print(classification_report(y_test, y_pred_model))
  print('\n')

## MODEL NAME : Nearest Neighbors
[[118   0   0   0   0   0   0   0   0]
 [  0  97   1  10   1   0   1   6   2]
 [  0   3  84   2   0   0   0   0   2]
 [  0  16   6  84   6   0   7   4   5]
 [  0   0   0   0  89   0   2   7   5]
 [  0   3   5  17   2  81   1   8   6]
 [  0   1   1   4   4   1  87   3   2]
 [  0   5   0   3  16   1  10  72   4]
 [  0   2   7   6  16   1   5   3  54]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       118
           1       0.76      0.82      0.79       118
           2       0.81      0.92      0.86        91
           3       0.67      0.66      0.66       128
           4       0.66      0.86      0.75       103
           5       0.96      0.66      0.78       123
           6       0.77      0.84      0.81       103
           7       0.70      0.65      0.67       111
           8       0.68      0.57      0.62        94

    accuracy                           0.77       989
   macro avg      

In [9]:
correlation = {}
label = clean_data['label']
for col in clean_data.columns:
  correlation[col] = label.corr(clean_data[col])
sorted_correlation = sorted(correlation.items(), key=lambda x: x[1])
print(sorted_correlation)
len(sorted_correlation)

[('6', -0.48281889841374537), ('dissimilarity_90_3', -0.4645584778666282), ('dissimilarity_90_4', -0.41825062400453916), ('5', -0.41366797014835227), ('30', -0.40651685793547016), ('36', -0.39929451047430564), ('dissimilarity_45_3', -0.3991413551037716), ('dissimilarity_135_3', -0.3960199677610974), ('0', -0.3885585383694986), ('165', -0.38807371133415486), ('4', -0.3822456275890178), ('20', -0.3806497036186852), ('dissimilarity_0_3', -0.37463732921776693), ('24', -0.37184337821033736), ('dissimilarity_90_5', -0.3691766874017605), ('3', -0.35851981443610714), ('35', -0.3560382380500233), ('50', -0.33991020455438026), ('25', -0.3364425404741739), ('dissimilarity_45_4', -0.3282284748067235), ('dissimilarity_135_4', -0.32541362308537297), ('dissimilarity_0_4', -0.32266471735810076), ('dissimilarity_90_6', -0.31695239893015165), ('66', -0.27192751583761116), ('83', -0.2618088356497494), ('42', -0.25312518624944375), ('34', -0.2446958080175656), ('75', -0.23478116019782636), ('43', -0.17198

448

In [10]:
positive_corr = {}
negative_corr = {}
for (k,v) in sorted_correlation:
  if(v>0):
    positive_corr[k] = v
  else:
    negative_corr[k] = v
len(positive_corr)

274

In [11]:
from sklearn.decomposition import PCA

pca = PCA(n_components = len(positive_corr))
x_train_pca = pca.fit_transform(x_train_scalled)
x_test_pca = pca.transform(x_test_scalled)

In [12]:
for name, model in zip(names, classifiers):
  model.fit(x_train_pca, y_train.values.ravel())
  y_pred_model = model.predict(x_test_pca)
  try:
    print(f'## MODEL NAME : {name}')
    print(confusion_matrix(y_test, y_pred_model))
    print(classification_report(y_test, y_pred_model))
    print('\n')
  except:
    print("Hello!!!!")

## MODEL NAME : Nearest Neighbors
[[118   0   0   0   0   0   0   0   0]
 [  0  97   1  10   1   0   1   6   2]
 [  0   3  84   2   0   0   0   0   2]
 [  0  16   6  84   6   0   7   4   5]
 [  0   0   0   0  89   0   2   7   5]
 [  0   3   5  17   2  81   1   8   6]
 [  0   1   1   4   4   1  87   3   2]
 [  0   5   0   3  16   1  10  72   4]
 [  0   2   7   6  16   1   5   3  54]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       118
           1       0.76      0.82      0.79       118
           2       0.81      0.92      0.86        91
           3       0.67      0.66      0.66       128
           4       0.66      0.86      0.75       103
           5       0.96      0.66      0.78       123
           6       0.77      0.84      0.81       103
           7       0.70      0.65      0.67       111
           8       0.68      0.57      0.62        94

    accuracy                           0.77       989
   macro avg      